### ISSUE TITLE
No delete button

### ISSUE THREAD

**Issue by excitedbox** [kaiakz/walv#10]
There is no way to delete a widget. 

Is the online demo the latest version or should i setup my own for testing?

**Comment by kaiakz** [comment]
The online demo isn't the latest version. The latest version is on the branch `vue`,  I will add the function to the latest version. I will merge the `vue` branch soon. :)

**Comment by excitedbox** [comment]
Awesome. I would love to help but no comments in the code make it hard to get a grasp on what is going on.

**Comment by kaiakz** [comment]
:smile: This project welcomes any contribution. Feel free to discuss your idea here. 
I am sorry for the lack of comments. I should add more comments this weekend.
