### ISSUE TITLE
LittlevGL support

### ISSUE THREAD

**Issue by ajithpv** [kaiakz/walv#4]
Hi,
Since there is one more repo already present for LittlevGL GUI in your account, I would like to know:
1. Is this repo still active?
2. Whether future support for LittlevGL versions will be available for walv
3. How walv and other LittlevGL gui designer distinguish each other? What is the use case of one to another?

**Comment by kaiakz** [comment]
Hi, I now working on this repo `walv` mainly. `lv_gui_designer` will be used for other purposes(planning), it will become a simple tool. 

>     2\. Whether future support for LittlevGL versions will be available for walv

`walv` and `lv_gui_designer` are based on v6.0(or latest version). Both of them generate the code for LittlevGL v6.0(or latest). But this is not absolute. Although lvgl v5.x does not support `event`, but it supports some common function(set_x, set_y, ect). Compared to the old version lvgl(v5.x), many v6.0 API are same. You can try generation code part.

>     3\. How walv and other LittlevGL gui designer distinguish each other? What is the use case of one to another?

Here is the problem. `lv_gui_designer` will be changed, but lvgl also has `lv_gui_builder`(For PC, written in pylvgl and QT). I manage a way that walv and other lvgl design tool can use the common Project File.
